import {
    PiAddressBookDuotone,
    PiBankDuotone,
    PiBuildingsDuotone,
    PiCalculatorDuotone,
    PiCalendarDuotone,
    PiChartBarDuotone,
    PiChartLineUpDuotone,
    PiClipboardTextDuotone,
    PiCreditCardDuotone,
    PiCubeDuotone,
    PiFactoryDuotone,
    PiFileTextDuotone,
    PiGearDuotone,
    PiGitBranchDuotone,
    PiHouseLineDuotone,
    PiPackageDuotone,
    PiPulseDuotone,
    PiReceiptDuotone,
    PiShoppingCartDuotone,
    PiStackDuotone,
    PiTableDuotone,
    PiTruckDuotone,
    PiUserCircleDuotone,
    PiUsersDuotone,
} from 'react-icons/pi'
import type { JSX } from 'react'

export type ErpIcons = Record<string, JSX.Element>

const erpIcon: ErpIcons = {
    home: <PiHouseLineDuotone />,
    shoppingCart: <PiShoppingCartDuotone />,
    package: <PiPackageDuotone />,
    warehouse: <PiBuildingsDuotone />,
    calculator: <PiCalculatorDuotone />,
    factory: <PiFactoryDuotone />,
    truck: <PiTruckDuotone />,
    users: <PiUsersDuotone />,
    userCircle: <PiUserCircleDuotone />,
    building: <PiBuildingsDuotone />,
    fileText: <PiFileTextDuotone />,
    fileSpreadsheet: <PiTableDuotone />,
    barChart: <PiChartBarDuotone />,
    lineChart: <PiChartLineUpDuotone />,
    settings: <PiGearDuotone />,
    cog: <PiGearDuotone />,
    layers: <PiStackDuotone />,
    boxes: <PiCubeDuotone />,
    clipboard: <PiClipboardTextDuotone />,
    receipt: <PiReceiptDuotone />,
    creditCard: <PiCreditCardDuotone />,
    landmark: <PiBankDuotone />,
    gitBranch: <PiGitBranchDuotone />,
    activity: <PiPulseDuotone />,
    calendar: <PiCalendarDuotone />,
    crm: <PiAddressBookDuotone />,
}

export default erpIcon
