'use client'

import { useEffect, useMemo, useState } from 'react'
import Dialog from '@/components/ui/Dialog'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'
import Alert from '@/components/ui/Alert'
import { Form, FormItem } from '@/components/ui/Form'
import type { Driver, TripCandidate } from '../../types'

type Option = { value: string; label: string }

type Props = {
    candidate: TripCandidate | null
    drivers: Driver[]
    busy: boolean
    onClose: () => void
    onCreate: (body: {
        loadPlanId: string
        driverId: string | null
        plannedStartAt: string | null
    }) => Promise<string | null>
}

/** Create a trip from a READY load plan. Stops are generated by the server from its cargo. */
export default function CreateTmsTripDialog({
    candidate,
    drivers,
    busy,
    onClose,
    onCreate,
}: Props) {
    const [driverId, setDriverId] = useState('')
    const [plannedStartAt, setPlannedStartAt] = useState('')
    const [error, setError] = useState<string | null>(null)

    useEffect(() => {
        if (!candidate) return
        setDriverId('')
        setPlannedStartAt('')
        setError(null)
    }, [candidate])

    const driverOptions = useMemo<Option[]>(
        () => [
            { value: '', label: 'Assign later' },
            ...drivers.map((d) => ({
                value: d.id,
                label: `${d.firstName} ${d.lastName}${d.employeeCode ? ` · ${d.employeeCode}` : ''} (${d.status})`,
            })),
        ],
        [drivers],
    )

    const submit = async () => {
        if (!candidate) return
        const err = await onCreate({
            loadPlanId: candidate.loadPlanId,
            driverId: driverId || null,
            plannedStartAt: plannedStartAt ? new Date(plannedStartAt).toISOString() : null,
        })
        if (err) setError(err)
        else onClose()
    }

    return (
        <Dialog isOpen={Boolean(candidate)} width={520} onClose={onClose} onRequestClose={onClose}>
            <h5 className="mb-1">Create trip</h5>
            {candidate ? (
                <p className="mb-4 text-sm text-gray-500">
                    {candidate.code} · {candidate.vehicle.plateNumber} · {candidate.totalQty}{' '}
                    items · {candidate.lineCount} line(s). Stops: {candidate.stopPreview.ship}{' '}
                    load, {candidate.stopPreview.to} delivery
                    {candidate.stopPreview.ret ? `, ${candidate.stopPreview.ret} return` : ''}.
                </p>
            ) : null}
            {error ? (
                <Alert showIcon type="danger" className="mb-4">
                    {error}
                </Alert>
            ) : null}
            <Form onSubmit={(e) => e.preventDefault()}>
                <FormItem label="Driver">
                    <Select
                        options={driverOptions}
                        value={driverOptions.find((o) => o.value === driverId) ?? driverOptions[0]}
                        onChange={(option) => setDriverId((option as Option | null)?.value ?? '')}
                    />
                </FormItem>
                <FormItem label="Planned start">
                    <Input
                        type="datetime-local"
                        value={plannedStartAt}
                        onChange={(e) => setPlannedStartAt(e.target.value)}
                    />
                </FormItem>
            </Form>
            <div className="mt-4 flex justify-end gap-2">
                <Button onClick={onClose}>Cancel</Button>
                <Button variant="solid" loading={busy} onClick={() => void submit()}>
                    Create trip
                </Button>
            </div>
        </Dialog>
    )
}
