-- AlterTable
ALTER TABLE "TripStop" ADD COLUMN IF NOT EXISTS "podSignatureUrl" TEXT;
ALTER TABLE "TripStop" ADD COLUMN IF NOT EXISTS "podPhotoUrl" TEXT;
ALTER TABLE "TripStop" ADD COLUMN IF NOT EXISTS "podNotes" TEXT;
ALTER TABLE "TripStop" ADD COLUMN IF NOT EXISTS "failureReason" TEXT;
