import { MM_EVENT_VERSIONS, type MmEventVersion } from './mm-integration-event.types'

export const MM_EVENT_CATEGORIES = {
    MASTER_DATA: 'MASTER_DATA',
    SUPPLIER: 'SUPPLIER',
    PROCUREMENT: 'PROCUREMENT',
    RECEIVING: 'RECEIVING',
    QUALITY: 'QUALITY',
    INVENTORY: 'INVENTORY',
    RESERVATION: 'RESERVATION',
    WAREHOUSE: 'WAREHOUSE',
    RETURNS: 'RETURNS',
    PLANNING: 'PLANNING',
    VALUATION: 'VALUATION',
} as const

export type MmEventCategory =
    (typeof MM_EVENT_CATEGORIES)[keyof typeof MM_EVENT_CATEGORIES]

export type MmEventCatalogEntry = {
    eventType: string
    category: MmEventCategory
    currentVersion: MmEventVersion
    supportedVersions: MmEventVersion[]
    sourceModule: string
    sourceEntityType: string
    financial: boolean
    persistsOutbox: boolean
    intendedConsumers: string[]
    description: string
}

/** Phase 3A typed integration event catalog for MM cross-module contracts. */
export const MM_EVENT_CATALOG: Record<string, MmEventCatalogEntry> = {
    // ── Master Data ──
    MaterialCreated: {
        eventType: 'MaterialCreated',
        category: MM_EVENT_CATEGORIES.MASTER_DATA,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'MATERIALS',
        sourceEntityType: 'MATERIAL',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'PRODUCTION', 'ANALYTICS'],
        description: 'New material master record created',
    },
    MaterialActivated: {
        eventType: 'MaterialActivated',
        category: MM_EVENT_CATEGORIES.MASTER_DATA,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'MATERIALS',
        sourceEntityType: 'MATERIAL',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'PRODUCTION', 'PROCUREMENT'],
        description: 'Material status changed to active',
    },
    MaterialBlocked: {
        eventType: 'MaterialBlocked',
        category: MM_EVENT_CATEGORIES.MASTER_DATA,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'MATERIALS',
        sourceEntityType: 'MATERIAL',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'PRODUCTION', 'PROCUREMENT'],
        description: 'Material blocked from procurement or usage',
    },

    // ── Supplier ──
    SupplierActivated: {
        eventType: 'SupplierActivated',
        category: MM_EVENT_CATEGORIES.SUPPLIER,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'SUPPLIER',
        sourceEntityType: 'SUPPLIER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['PROCUREMENT', 'FICO', 'ANALYTICS'],
        description: 'Supplier activated for procurement',
    },
    SupplierBlocked: {
        eventType: 'SupplierBlocked',
        category: MM_EVENT_CATEGORIES.SUPPLIER,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'SUPPLIER',
        sourceEntityType: 'SUPPLIER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['PROCUREMENT', 'FICO'],
        description: 'Supplier blocked from new POs',
    },

    // ── Procurement ──
    PurchaseRequisitionApproved: {
        eventType: 'PurchaseRequisitionApproved',
        category: MM_EVENT_CATEGORIES.PROCUREMENT,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PROCUREMENT',
        sourceEntityType: 'PURCHASE_REQUISITION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['NOTIFICATIONS', 'PROCUREMENT'],
        description: 'PR approved via workflow',
    },
    PurchaseOrderApproved: {
        eventType: 'PurchaseOrderApproved',
        category: MM_EVENT_CATEGORIES.PROCUREMENT,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PROCUREMENT',
        sourceEntityType: 'PURCHASE_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['NOTIFICATIONS', 'RECEIVING', 'FICO'],
        description: 'PO approved via workflow',
    },
    PurchaseOrderSent: {
        eventType: 'PurchaseOrderSent',
        category: MM_EVENT_CATEGORIES.PROCUREMENT,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PROCUREMENT',
        sourceEntityType: 'PURCHASE_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SUPPLIER_PORTAL', 'NOTIFICATIONS'],
        description: 'PO transmitted to supplier',
    },
    PurchaseOrderCancelled: {
        eventType: 'PurchaseOrderCancelled',
        category: MM_EVENT_CATEGORIES.PROCUREMENT,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PROCUREMENT',
        sourceEntityType: 'PURCHASE_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['RECEIVING', 'NOTIFICATIONS', 'FICO'],
        description: 'PO cancelled',
    },
    PurchaseOrderOverdue: {
        eventType: 'PurchaseOrderOverdue',
        category: MM_EVENT_CATEGORIES.PROCUREMENT,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'PROCUREMENT',
        sourceEntityType: 'PURCHASE_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['NOTIFICATIONS', 'SUPPLIER_PERFORMANCE'],
        description: 'PO past expected delivery date',
    },

    // ── Receiving ──
    ExpectedReceiptCreated: {
        eventType: 'ExpectedReceiptCreated',
        category: MM_EVENT_CATEGORIES.RECEIVING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INBOUND',
        sourceEntityType: 'EXPECTED_RECEIPT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['RECEIVING', 'WAREHOUSE'],
        description: 'Expected receipt scheduled from PO',
    },
    ASNReceived: {
        eventType: 'ASNReceived',
        category: MM_EVENT_CATEGORIES.RECEIVING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INBOUND',
        sourceEntityType: 'ASN',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['RECEIVING', 'WAREHOUSE'],
        description: 'Advance ship notice recorded',
    },
    ReceivingValidated: {
        eventType: 'ReceivingValidated',
        category: MM_EVENT_CATEGORIES.RECEIVING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'RECEIVING_DOCUMENT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['QUALITY', 'WAREHOUSE'],
        description: 'Receiving document validated',
    },
    ReceivingPosted: {
        eventType: 'ReceivingPosted',
        category: MM_EVENT_CATEGORIES.RECEIVING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'RECEIVING_DOCUMENT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['QUALITY', 'STOCK_OPS'],
        description: 'Receiving document posted',
    },
    ReceivingCompleted: {
        eventType: 'ReceivingCompleted',
        category: MM_EVENT_CATEGORIES.RECEIVING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'RECEIVING_DOCUMENT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['STOCK_OPS', 'QUALITY'],
        description: 'Receiving process completed',
    },
    GoodsReceiptPosted: {
        eventType: 'GoodsReceiptPosted',
        category: MM_EVENT_CATEGORIES.RECEIVING,
        currentVersion: MM_EVENT_VERSIONS.V2,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'STOCK_OPS',
        sourceEntityType: 'GOODS_RECEIPT',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'WAREHOUSE', 'VALUATION'],
        description: 'Goods receipt posted to inventory',
    },

    // ── Quality ──
    InspectionLotCreated: {
        eventType: 'InspectionLotCreated',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'INSPECTION_LOT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['QUALITY', 'NOTIFICATIONS'],
        description: 'Inspection lot created for receiving',
    },
    QualityDecisionMade: {
        eventType: 'QualityDecisionMade',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V2,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'QUALITY_INSPECTION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['WAREHOUSE', 'INVENTORY', 'SUPPLIER_PERFORMANCE'],
        description: 'Usage decision recorded on inspection lot',
    },
    UsageDecisionRecorded: {
        eventType: 'UsageDecisionRecorded',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'QUALITY_INSPECTION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['WAREHOUSE', 'INVENTORY'],
        description: 'Legacy alias for quality usage decision',
    },
    QualityHoldCreated: {
        eventType: 'QualityHoldCreated',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'QUALITY_HOLD',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['INVENTORY', 'NOTIFICATIONS'],
        description: 'Stock placed on quality hold',
    },
    QualityHoldReleased: {
        eventType: 'QualityHoldReleased',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'QUALITY_HOLD',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['INVENTORY', 'WAREHOUSE'],
        description: 'Quality hold released',
    },
    QualityAccepted: {
        eventType: 'QualityAccepted',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'INSPECTION_LOT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SUPPLIER_PERFORMANCE', 'WAREHOUSE'],
        description: 'Inspection lot accepted',
    },
    QualityRejected: {
        eventType: 'QualityRejected',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'INSPECTION_LOT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SUPPLIER_PERFORMANCE', 'NOTIFICATIONS'],
        description: 'Inspection lot rejected',
    },
    SupplierQualityIncident: {
        eventType: 'SupplierQualityIncident',
        category: MM_EVENT_CATEGORIES.QUALITY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'INSPECTION_LOT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SUPPLIER_PERFORMANCE', 'ANALYTICS'],
        description: 'Supplier quality incident recorded',
    },
    PutawayRequested: {
        eventType: 'PutawayRequested',
        category: MM_EVENT_CATEGORIES.WAREHOUSE,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'INSPECTION_LOT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['WAREHOUSE'],
        description: 'Putaway task requested after quality acceptance',
    },
    SupplierReturnRequested: {
        eventType: 'SupplierReturnRequested',
        category: MM_EVENT_CATEGORIES.RETURNS,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RECEIVING',
        sourceEntityType: 'SUPPLIER_RETURN',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['RETURNS_DISPOSAL'],
        description: 'Supplier return requested from quality rejection',
    },

    // ── Inventory ──
    GoodsIssuePosted: {
        eventType: 'GoodsIssuePosted',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V2,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'STOCK_OPS',
        sourceEntityType: 'GOODS_ISSUE',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'SD', 'PRODUCTION'],
        description: 'Goods issue posted to inventory',
    },
    InventoryTransactionPosted: {
        eventType: 'InventoryTransactionPosted',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V2,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'INVENTORY_TRANSACTION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['AUDIT', 'TRACEABILITY', 'ANALYTICS'],
        description: 'Inventory ledger transaction posted',
    },
    InventoryTransactionReversed: {
        eventType: 'InventoryTransactionReversed',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'INVENTORY_TRANSACTION',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'AUDIT'],
        description: 'Inventory transaction reversed',
    },
    InventoryAdjusted: {
        eventType: 'InventoryAdjusted',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V2,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'STOCK_OPS',
        sourceEntityType: 'ADJUSTMENT',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'ANALYTICS'],
        description: 'Inventory adjustment posted',
    },
    InventoryTransferred: {
        eventType: 'InventoryTransferred',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V2,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'WAREHOUSE',
        sourceEntityType: 'WM_TRANSFER',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'WAREHOUSE'],
        description: 'Inter-warehouse transfer posted',
    },
    StockStatusChanged: {
        eventType: 'StockStatusChanged',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'INVENTORY_BALANCE',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['AUDIT', 'ANALYTICS'],
        description: 'Stock status changed (unrestricted/quality/blocked)',
    },

    // ── Reservation / Allocation ──
    ReservationCreated: {
        eventType: 'ReservationCreated',
        category: MM_EVENT_CATEGORIES.RESERVATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'RESERVATION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'WAREHOUSE', 'NOTIFICATIONS'],
        description: 'Stock reservation created',
    },
    ReservationReleased: {
        eventType: 'ReservationReleased',
        category: MM_EVENT_CATEGORIES.RESERVATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'RESERVATION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'AVAILABILITY'],
        description: 'Stock reservation released or fulfilled',
    },
    AllocationCreated: {
        eventType: 'AllocationCreated',
        category: MM_EVENT_CATEGORIES.RESERVATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'ALLOCATION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'WAREHOUSE'],
        description: 'Hard allocation created against demand',
    },
    AllocationReleased: {
        eventType: 'AllocationReleased',
        category: MM_EVENT_CATEGORIES.RESERVATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'ALLOCATION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'AVAILABILITY'],
        description: 'Allocation released',
    },
    ShortageDetected: {
        eventType: 'ShortageDetected',
        category: MM_EVENT_CATEGORIES.RESERVATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'INVENTORY',
        sourceEntityType: 'SALES_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'NOTIFICATIONS', 'PROCUREMENT'],
        description: 'Demand reservation could not fully cover requested quantity',
    },

    // ── SD → MM demand events (registered for cross-module contract) ──
    SalesOrderConfirmed: {
        eventType: 'SalesOrderConfirmed',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'SD',
        sourceEntityType: 'SALES_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['MM'],
        description: 'Sales order confirmed — triggers ATP check and reservation',
    },
    SalesOrderCancelled: {
        eventType: 'SalesOrderCancelled',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'SD',
        sourceEntityType: 'SALES_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['MM'],
        description: 'Sales order cancelled — releases MM reservations',
    },
    SalesDemandChanged: {
        eventType: 'SalesDemandChanged',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'SD',
        sourceEntityType: 'SALES_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['MM'],
        description: 'Sales order line quantity changed — partial reservation release',
    },

    // ── PP → MM demand events ──
    ProductionOrderReleased: {
        eventType: 'ProductionOrderReleased',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PRODUCTION',
        sourceEntityType: 'PRODUCTION_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['MM'],
        description: 'Production order released — triggers ATP check and component reservation',
    },
    ProductionMaterialRequirementCreated: {
        eventType: 'ProductionMaterialRequirementCreated',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PRODUCTION',
        sourceEntityType: 'PRODUCTION_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['MM'],
        description: 'Production component demand created — triggers MM reservation',
    },
    ProductionOrderCancelled: {
        eventType: 'ProductionOrderCancelled',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PRODUCTION',
        sourceEntityType: 'PRODUCTION_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['MM'],
        description: 'Production order cancelled — releases MM reservations',
    },
    ProductionMaterialRequirementChanged: {
        eventType: 'ProductionMaterialRequirementChanged',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PRODUCTION',
        sourceEntityType: 'PRODUCTION_ORDER',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['MM'],
        description: 'Production component quantity changed — partial reservation release',
    },

    // ── Warehouse execution ──
    PutawayCompleted: {
        eventType: 'PutawayCompleted',
        category: MM_EVENT_CATEGORIES.WAREHOUSE,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'WAREHOUSE',
        sourceEntityType: 'PUTAWAY_TASK',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['INVENTORY', 'ANALYTICS'],
        description: 'Putaway task completed',
    },
    PickingCompleted: {
        eventType: 'PickingCompleted',
        category: MM_EVENT_CATEGORIES.WAREHOUSE,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'WAREHOUSE',
        sourceEntityType: 'PICK_TASK',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['INVENTORY', 'SD'],
        description: 'Pick task completed',
    },
    PackingCompleted: {
        eventType: 'PackingCompleted',
        category: MM_EVENT_CATEGORIES.WAREHOUSE,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'WAREHOUSE',
        sourceEntityType: 'PACKING_SESSION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['SD', 'LOGISTICS'],
        description: 'Packing session completed',
    },

    // ── Returns / Disposal ──
    SupplierReturnPosted: {
        eventType: 'SupplierReturnPosted',
        category: MM_EVENT_CATEGORIES.RETURNS,
        currentVersion: MM_EVENT_VERSIONS.V2,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RETURNS_DISPOSAL',
        sourceEntityType: 'SUPPLIER_RETURN',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'SUPPLIER_PERFORMANCE'],
        description: 'Supplier return posted',
    },
    CustomerReturnPosted: {
        eventType: 'CustomerReturnPosted',
        category: MM_EVENT_CATEGORIES.RETURNS,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RETURNS_DISPOSAL',
        sourceEntityType: 'CUSTOMER_RETURN',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'SD'],
        description: 'Customer return posted',
    },
    DisposalPosted: {
        eventType: 'DisposalPosted',
        category: MM_EVENT_CATEGORIES.RETURNS,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RETURNS_DISPOSAL',
        sourceEntityType: 'DISPOSAL',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'ANALYTICS'],
        description: 'Disposal document posted',
    },
    ScrapPosted: {
        eventType: 'ScrapPosted',
        category: MM_EVENT_CATEGORIES.RETURNS,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'RETURNS_DISPOSAL',
        sourceEntityType: 'SCRAP',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'ANALYTICS'],
        description: 'Scrap posting completed',
    },

    // ── Planning ──
    MRPCompleted: {
        eventType: 'MRPCompleted',
        category: MM_EVENT_CATEGORIES.PLANNING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PLANNING',
        sourceEntityType: 'MRP_RUN',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['PROCUREMENT', 'NOTIFICATIONS', 'ANALYTICS'],
        description: 'MRP run completed',
    },
    MRPShortageDetected: {
        eventType: 'MRPShortageDetected',
        category: MM_EVENT_CATEGORIES.PLANNING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PLANNING',
        sourceEntityType: 'MATERIAL_REQUIREMENT',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['NOTIFICATIONS', 'PROCUREMENT'],
        description: 'MRP detected material shortage',
    },
    ProcurementSuggestionCreated: {
        eventType: 'ProcurementSuggestionCreated',
        category: MM_EVENT_CATEGORIES.PLANNING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'PLANNING',
        sourceEntityType: 'PROCUREMENT_SUGGESTION',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['PROCUREMENT', 'NOTIFICATIONS'],
        description: 'MRP procurement suggestion created',
    },
    StockBelowSafetyLevel: {
        eventType: 'StockBelowSafetyLevel',
        category: MM_EVENT_CATEGORIES.PLANNING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'PLANNING',
        sourceEntityType: 'MATERIAL',
        financial: false,
        persistsOutbox: true,
        intendedConsumers: ['NOTIFICATIONS', 'PROCUREMENT'],
        description: 'Available stock below safety level',
    },

    // ── Valuation ──
    InventoryValuationUpdated: {
        eventType: 'InventoryValuationUpdated',
        category: MM_EVENT_CATEGORIES.VALUATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'VALUATION',
        sourceEntityType: 'MATERIAL_VALUATION',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'ANALYTICS'],
        description: 'Material valuation updated',
    },
    LandedCostAllocated: {
        eventType: 'LandedCostAllocated',
        category: MM_EVENT_CATEGORIES.VALUATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'VALUATION',
        sourceEntityType: 'LANDED_COST',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO', 'VALUATION'],
        description: 'Landed cost allocated to receipt layers',
    },
    PriceVariancePosted: {
        eventType: 'PriceVariancePosted',
        category: MM_EVENT_CATEGORIES.VALUATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'VALUATION',
        sourceEntityType: 'PRICE_VARIANCE',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO'],
        description: 'Purchase price variance posted',
    },
    InventoryRevaluationPosted: {
        eventType: 'InventoryRevaluationPosted',
        category: MM_EVENT_CATEGORIES.VALUATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1, MM_EVENT_VERSIONS.V2],
        sourceModule: 'VALUATION',
        sourceEntityType: 'INVENTORY_VALUATION',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO'],
        description: 'Inventory revaluation posted',
    },
    InventoryValuationReversed: {
        eventType: 'InventoryValuationReversed',
        category: MM_EVENT_CATEGORIES.VALUATION,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'VALUATION',
        sourceEntityType: 'INVENTORY_VALUATION',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO'],
        description: 'Inventory valuation reversed',
    },
    GoodsReceiptReversed: {
        eventType: 'GoodsReceiptReversed',
        category: MM_EVENT_CATEGORIES.RECEIVING,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'STOCK_OPS',
        sourceEntityType: 'GOODS_RECEIPT',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO'],
        description: 'Goods receipt reversed',
    },
    GoodsIssueReversed: {
        eventType: 'GoodsIssueReversed',
        category: MM_EVENT_CATEGORIES.INVENTORY,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'STOCK_OPS',
        sourceEntityType: 'GOODS_ISSUE',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO'],
        description: 'Goods issue reversed',
    },
    DisposalReversed: {
        eventType: 'DisposalReversed',
        category: MM_EVENT_CATEGORIES.RETURNS,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RETURNS_DISPOSAL',
        sourceEntityType: 'DISPOSAL',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO'],
        description: 'Disposal document reversed',
    },
    SupplierReturnReversed: {
        eventType: 'SupplierReturnReversed',
        category: MM_EVENT_CATEGORIES.RETURNS,
        currentVersion: MM_EVENT_VERSIONS.V1,
        supportedVersions: [MM_EVENT_VERSIONS.V1],
        sourceModule: 'RETURNS_DISPOSAL',
        sourceEntityType: 'SUPPLIER_RETURN',
        financial: true,
        persistsOutbox: true,
        intendedConsumers: ['FICO'],
        description: 'Supplier return reversed',
    },
}

export function getEventCatalogEntry(
    eventType: string,
): MmEventCatalogEntry | undefined {
    return MM_EVENT_CATALOG[eventType]
}

export function isFinancialEvent(eventType: string): boolean {
    return getEventCatalogEntry(eventType)?.financial === true
}

export function isCataloguedEvent(eventType: string): boolean {
    return eventType in MM_EVENT_CATALOG
}

export function listCatalogEvents(): MmEventCatalogEntry[] {
    return Object.values(MM_EVENT_CATALOG)
}

export function getFinancialEventTypes(): string[] {
    return listCatalogEvents()
        .filter((e) => e.financial)
        .map((e) => e.eventType)
}

export function resolveEventVersion(
    eventType: string,
    requested?: MmEventVersion,
): MmEventVersion {
    const entry = getEventCatalogEntry(eventType)
    if (!entry) {
        return requested ?? MM_EVENT_VERSIONS.V1
    }
    if (requested && entry.supportedVersions.includes(requested)) {
        return requested
    }
    return entry.currentVersion
}
